// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTf6FWaqhLd1sAsy-JmygkH7DkPzol7WY',
    appId: '1:144502365323:web:f782ebc9c3a182e38a088e',
    messagingSenderId: '144502365323',
    projectId: 'voiz-android',
    authDomain: 'voiz-android.firebaseapp.com',
    storageBucket: 'voiz-android.firebasestorage.app',
    measurementId: 'G-G73GDJ8175',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARz5pmY6SZgL_feXnsSpUCngFfInaSQyY',
    appId: '1:144502365323:android:11a21244ab5ee44b8a088e',
    messagingSenderId: '144502365323',
    projectId: 'voiz-android',
    storageBucket: 'voiz-android.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4QqT0L84TiunmhwgrkWIujHgTA1yTOrQ',
    appId: '1:144502365323:ios:ee0c01f13ad42f0b8a088e',
    messagingSenderId: '144502365323',
    projectId: 'voiz-android',
    storageBucket: 'voiz-android.firebasestorage.app',
    androidClientId: '144502365323-9hko1rj6g01bl4dv845a25qoinq7cs1r.apps.googleusercontent.com',
    iosClientId: '144502365323-mc3odeubd0282oopulpt00dfhn4bm1pm.apps.googleusercontent.com',
    iosBundleId: 'com.voizapp.voiceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4QqT0L84TiunmhwgrkWIujHgTA1yTOrQ',
    appId: '1:144502365323:ios:ee0c01f13ad42f0b8a088e',
    messagingSenderId: '144502365323',
    projectId: 'voiz-android',
    storageBucket: 'voiz-android.firebasestorage.app',
    androidClientId: '144502365323-9hko1rj6g01bl4dv845a25qoinq7cs1r.apps.googleusercontent.com',
    iosClientId: '144502365323-mc3odeubd0282oopulpt00dfhn4bm1pm.apps.googleusercontent.com',
    iosBundleId: 'com.voizapp.voiceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTf6FWaqhLd1sAsy-JmygkH7DkPzol7WY',
    appId: '1:144502365323:web:e836e620dbd50e418a088e',
    messagingSenderId: '144502365323',
    projectId: 'voiz-android',
    authDomain: 'voiz-android.firebaseapp.com',
    storageBucket: 'voiz-android.firebasestorage.app',
    measurementId: 'G-NH1ZRSB19M',
  );

}